#+HTML_LINK_HOME: index.html
#+HTML_LINK_UP: index.html
#+title: Going Phone-/less/
#+author: Jackson
#+date: 2/22/25
#+setupfile: ./retro_dark.theme
#+options: toc:nil num:nil html-style:nil timestamp:nil org-footnote-section:t

/A collection of my thoughts as I transition to a lifestyle of using my phone less./

* _Introduction_
Around December of last year I experienced a level of boredom that I hadn't felt in a long while. This led me to downloading a game on my phone, which filled my idle hours for a week or two before I asked myself, why? This may sound like I am overanalyzing the importance of a silly game on my phone, but the shift in behavior for me felt strange. I hadn't felt the temptation to play a mobile game in 4–5 years, and even when I was playing the game it brought me no satisfaction.

This seemingly innocent act of downloading a game caused me to rethink the way that I interract with my technology. As a computer science student and researcher I spend a minimum of 8 hours a day working on a computer, which for those in my field is likely not to change. I've come to accept that a large portion of my work will have to be done in front of a screen, which has also led to me think about how I can minimize screen usage in other portions of my life.

Taking a serious look at my technology usage is not a new thing for me either. There have been many times in my life where I have on a whim cut out a particular usage of technology in my life. The issue is that I never had the support structure ready to facilitate these changes, so the negative aspects of other technology usage was often amplified.

Though this post I hope to cover my journey in the past, and what has recently caused a far more drastic shift in the was I interract with technology.

* _Early Smartphone Days_
** _Social Media_
As part of Gen Z I got my first smartphone around the time when most of my friends did, which for me was 7th grade. I distinctly remember the first thing I did with my phone was download instagram and make an account. It was just an instinct to do so, as everyone around me had been talking about it, or showing me how to use it. After getting the app I proceeded to download all sorts of other games and "useful" apps.

Quickly, checking Instagram because a habit, as did playing the various games that required constant attention to ensure I was maximizing my "productivity" in them. At this point in my life I would classifiy this behavior as technology maximalizm. I wanted to ensure that I had every possible stream of entertainment or utility available to me on my phone. However, outside the time spent gaming, my phone wasn't really an issue. I was easily able to put it down and not htink about it for long periods of time, which meant that I didn't see it as an issue.

Fast-forward a few more years after getting my first phone, and it had now become an issue. At first Instagram start as a convenient way to see what my friends were up to, but looking back on it now, this was of little to no use for me. Especially at that age, my only friends were the ones that I saw at school every day, so checking on their Instagram posts was just replacing time that I could have already spent face-to-face with them. Instead of sitting at the lunch table talking with each other we were instead distracted by our phones "keeping up" with the people sat across from us.

I so deperatly wanted to be recognized by my peers that I would spend the bus rides to and from school liking /every single post/ on my feed (which was much easier back when the feed was chronological). This behavior harmed the way I interracted with Instagram, as I no longer spent the time looking through each post, instead scrolling as fast as I possibly could only stopping to double-tap to like. Luckily, this behavior didn't last long and around the time I started high-school (2014-2015) I had reduced my following count back down to just my closest friends.

*** Turning Point
One of the intersting things that I observe looking back on my teenage social media usage was the shift from chronological feels to algorithmic feeds. Before the shift to algorithmic feeds I never felt a desire to scroll down some amount and then pop back up to the top to refresh the feed. I was a much simpler interraction platform, I scrolled until I was all caught up (I'm pretty sure they even used to tell you this directly?), and then closed the app because there was /literally/ nothing new to look at. There was no temptation
to spend more time than necessary on the platform.

Once these platforms shifted to algorithmic feeds, and especially showing you content on your home page that you didn't follow, there was a never ending firehose of pictures to look at. Even if you never scrolled past the first picture on your feed, you could infinitely refresh the feed and be served a new picture at the top each time. Interestingly, this lead to me refreshing the feed more to see if there was something new, as I was no longer garunteed that the new pictures would be at the top of my feed, meaning I could have potentially missed out.

#+begin_example
I relate this to my struggle with sound based notifications on any platform. On the one hand I'd love to not have my phone (or computer) always nearby, so sound based notifications are a great alternative as I am much less likely to miss a timely notification. But, on the other hand the barrier to steal my attention is now gated behind a simple sound. Even if we restrict these notifications to only come through from our closest friends, we have no garuntee that their message even required our instant attention. So part of me prefers to keep notifications on so that I only use my phone we prompted, and the other part of me does not want to be prompted by a device, so I set aside time to manually comb through notifications. More on this later.
#+end_example

*** Warning Signs
Even at this time we were already being warned of the potential harms of social media. The big talking point was the /Fear of Missing Out/ or FOMO. As I'm sure you know, people tend to post only the positive aspects of their life on social media, which can lead to a sort of bragging contest between friend groups. If one friend wasn't able to make it on a trip, and they saw everyone else posting about it, they are /missing out/, which can quickly lead to anxiety, depression, or both.

Another potential downside often discussed was the fueling of body dysmorphia. It was well known that some models and other popular influencers (was this even a word back then?), were "touching-up" or "photoshopping" their photos before posting them online. This lead to a generation of people subconciously feeling presure to look like them, even at the detrement of their own health. One of the key issues here was that people felt a desire to "fit-in", without taking into consideration that these pictures might not be telling the whole truth.

With that in might my social media usage did reduce, even if very slightly. However, as will become a theme in this story, as I shut the door on one part of distraction, another opened to fill the void.

** _Gaming_
In high school we would take lots of trips for both band and choir, which meant filling hours of bus rides and waiting around. This lead to large groups gathering around specific mobile games that we would play as we waited for the next obligation. The social aspect of playing the game was a benefit in my eyes, the issue came with the desire to "keep up". Most people would play fairly casually, but some would spend hours outside of group play attempting to level up, which lead to more and more members of the group doing the same. What was once a casual group activity, turned into a hardcore and rigid exercise in one-upping each other.

This led me into a constant feeling that I had to play these games on my own time, so that I wasn't left out the next time the group was playing. Which quickly turned a light-hearted source of entertainment into a chore. The main issue here wasn't even the gaming in general, it was how easily accessible the mobile games were. As I highlighted before, I was able to put my phone down for long periods of time when I first got it, yet, fast-forward 2–3 years and I couldn't set the thing down. Every small moment of downtime or boredom could easily be filled by checking in on a game.

Contrast this with console of PC gaming, which while still a problem, were much less accessible at the time. While you could spend hours and hours playing video games at home on your computer, at least that was (hopefully) the only thing that you were doing. Mobile games were so easily accessible they could easily fill the brief 10-minute gap between classes, or even be tempting enough to play during class. And this is exactly what I did, spending every moment of downtime playing these games.

My school did a very poor job of enforcing no cell-phone policies during the school day, which I honestly cannot blame them for. We were really the first generation with access to unprecedented levels of easily accessible distractions. So to that end, cell phone usage only proliferated during my high school years, with the older generations recognizing the issue, and my generation "having fun".

*** Positives
I want to say that while gaming is a large time sink, I also think that it brought some positives to my life. It heavily inspired my passion for technology, and specifically software. Learning how to first set up a Minecraft server was a daunting task, but it introduced me to many of the fundamental software concepts that I now utilize daily.

In the same vein, I spent most of my gaming years in a pre-discord time. If you gamed with friends back then you may remember the struggle of what communication software to use. My friends and I explored many different options, but this lead us to think critically about what software we were choosing, even if we have no idea what "self-hosting" a teamspeak sever even meant.

** _Instant Message_
I am going to use instant messaging as a more broad term than it was originally coined for. I'll lump anything that presents itself as synchronous yet not face-to-face or voice based together. This includes things like Snapchat, Instagram DMs, and yes even texting itself, however that requires a bit more nuance. Texting can be entire asynchronous, think of the extreme of texting someone with a 12-hour time difference, where you may only get to send one message at a time, without sitting around waiting for their response. What I am referring to is the constant act of texting, then waiting on a response that most of these platforms now offer.

iMessage has the "..." bubble indicating someone is typing, Snapchat tells you when someone is even on the chat screen, and I'm sure Instagram does something similar, I just don't remember. These features may seem like a convenience at first, but I have only ever observed them being harmful additions. Someone may have sent a slightly confrontational message, and instead of walking away they will sit anxiously staring at the typing indicator waiting on a response. I can only imagine this is not healthy for our brains.

Even without considering confrontational message, you can observe the same behavior when couples or friend groups seek constant connection. Look around, and you'll see people out on a nice activity with their family, yet they feel a constant pull to their phone to keep up with what every one else is doing. They somehow feel tied to this attention sink, as if they will be harmed if they don't, and this fear of harm can be very real. I distinctly remember not responding to a group chat for 4 or 5 hours while at an Oktoberfest event with my family and then be excluded from plans later that evening. Now, should I have continued being friends with that group after the event? Probably not, but that is a whole other can of worms.

Back then the constant tie to the phone was perpetuated by /FOMO/, or simply a relationship that required constant reassurance that no I am not mad at you because I haven't replied in 5 minutes. This tie was so strong that I could never put my phone down any more. Even during music performances, I always ensured that my phone was tucked into my choir robe, my band tux, or even my marching band uniform. When I was out with my family I would pop my phone out under the table, so I could interract with a conversation virtually, instead of interrating with the people sitting next to me.

We'll get to the current day later in the post, but I just wanted to highlight some aspects of this constant connection mindset here, as they were present back in high school for me, just as much as they are present today, the part that has changed are the demands.

* _Transition Period_
Around the time when I graduated from high school I felt what was by far the strongest pull to stay connected. No longer did I have the same group of 7 or so friends with me 5 days of the week, or the rigid schedule to keep me busy. I started college and felt extremely lonely, which meant that instead of making new relationships with the people around me, I felt an even stronger pull to hold onto previous relationships. This meant I was almost never physically present with those around me, choosing instead to lean into the ability to be constantly connected with my friends virtually. I was still able to hang out with these friends a few times a week, but the drastic change was hard to get used to.

At this point my social media usage was also picking back up again, as was gaming to fill any downtime. This is also right around the time period of COVID-19, which shook up the entire world. In the span of 2 years I went from a strict 5 day a week high school schedule, to a brief 2 semesters of (relatively) unstructed college, to the Zoom call lifestyle that was COVID. And what did we do to relax after spending a few hours on a Zoom call? Well of course we got on a smaller screen to reward ourselves for all that hard work by watching TikToks.

TikTok was a particularly bad one for me, yet luckily I was able to see how bad it was quickly. However, once TikTok had taken off every other social media platform quickly raced to replicate the short-form content carouselle that they brought to the mainstream. So even though I was able to ditch TikTok directly, it was replaced first by SnapChats version, then Instagram, and eventually YouTube.

Throughout COVID my behavior rarely changed, just moving from one entertainment platform to the next. As the short-form content wave made its way through various social media platforms I attempted to find ways to disable it so that I could still get what I thought were "positive" interractions out of these platforms. I think at the time the only one I could disable was SnapChat's, but that just shifted my attention to Instagram.

As I began to think a bit more seriously about my health, as I'm sure a lot of us did during COVID, part of my attention went into evaluating the benefit of these platforms. SnapChat was the first to go, as it was only used for group chat communication, which could easily move to more traditional SMS. This was my first taste of the friction leaving these platforms causes between friends. While there is no functional difference between platforms, people have preferences. My friend group had long been split between an iMessage groupchat and an equivalent SnapChat one. Moving off of SnapChat meant I missed part of the conversation, but more importantly for me, it showed me that I was having to put up a large amount of effort to maintain a relationship, that the other side was not matching.

Moving away gave the rest of the friend group slightly more friction in communicating with me, and that caused a large falling out. As mentioned before, this was the same friend group that had previously excluded me from plans after not communicating with them while I was out with family, and yes, once again, probably should not have stuck around. But in the end this was the best choice for me as I had now eliminated one source of temptation to be on my phone.

At the time I was maintaining 3 separate Instagram accounts, my main personal page, one for my coffee business, and another for photography. Getting notifications from all 3 services was more than overwhelming, so I disabled notifications from everything but my personal account. This was a step in the right direction, but once again /FOMO/ hit hard, and I was then probably spending more time checking in with these services because I may have possibly missed an important notification. However around the same time I was questioning why even have an Instagram acount?

This was an important question as the only benefit it was giving me was the illusion of maintaining relationships with people I would likely never see again (old high school friends), or people I interracted with on a daily basis face-to-face.

#+begin_example
As a quick aside, something I have been thinking a lot about lately is the effort that I put into maintaining relationships with people that I don't interract with frequently (which I'm considering to be at least yearly, although even that is flexible). Now of course I'm not talking about extended family, those relationships are much stronger in my opinion, even if you do not see every single person face-to-face quite frequently. What I am talking about are past friends that you won't see frequently, and you can tell the desire to maintain the relationship is fading (from either side). It just seems like a lot of mental energy to maintain a fairly shallow relationship with someone when you can instead put that effort into building relationships with the people you see face-to-face on a daily basis.

I am nowhere near a fully formed opinion on this topic, it is just something that I have been considering as I try to be more intentional about where I am spending my mental energy.
#+end_example

Even aside from the question above I was using Instagram (on my personal account) as a read-only social media platform by this point. I had grown disinterested in sharing all aspects of my personal life, and didn't really have anything that interesting to comment on anyone's posts. This lead to me a brief stint of unfollowing everyone that I did not interract with on a regular basis. Although this change did help in the short term it didn't change the overall way I interracted with the platform. So not too long after I decided to delete all 3 of my Instagram acounts. Annoyingly, Instagram does not let you directly delete accounts, instead opting for a 30 day "deactivation" period, after which your account will be deleted. I had no temptation to get back on Instagram during these 30 days, so eventually my accounts were removed.

At this point I was left with only 2 real sources of social media on my phone, YouTube and Reddit. I find extremely valuable information from both platforms, YouTube has the best selection of infotainment content, and Reddit is invaluable as a beginner to programming. However, I didn't spend the majority of time on these platforms learning things, instead I wasted large blocks of time on meaningless entertainment. It never felt good getting up after watching 3–4 hours of YouTube in one sitting, just to move to another part of the house and start all over again. Reddit was far more accessible than watching a video, so that filled the random gaps in my day when I felt boredom.

Things were going well for a while there, I had eliminated all the traditional forms of social media from my life, and was reducing the time spent on my phone, yet my progress stagnated shortly after making the last changes. Then it got worse for another long period.

** _Podcasts_
I want to start by saying there is nothing inherrently wrong with listening to podcasts (or many of the other sources of content consumption), it just comes down to how you use it. For me the way I used podcasts was to always have something in my ears no matter what time of day or what I was doing. It's a hard decision becuase in the era of always needing to be productive, why would you not want to be twice as productive by listenting to a podcast while performing some other task. The answer for me was obvious, so I started subscribing to vast number of podcasts so that my feed would never be empty. This now meant I was conditioning myself so always needs some form of stimulation while doing basically anything in my life.

On the surface this was a net positive, as my iPhone reported decreased screen time, but that number doesn't tell the whole story. I can garuntee that as a whole I was consuming much more content during this time of my life. Not only that, I continued to watch just as much YouTube and read just as much Reddit as I did before starting to listenting to podcasts. The change was I was now filling every possible moment of silence (literally or figuratively) with podcasts.

This is a hard one for me to critique as I feel this was an imense period of growth for me. I learned so much of my computer science knowledge during this time, and I doubt I would be anywhere near a knowledgeable on a vast number of topics without all the podcasts I listened to. However, as we will discuss later, the issue here was how (and more specifically when) I was consuming these podcasts. I was a large mental hurdle for me to realize that I don't always need to be 2x productive by listenting to a podcast, I should instead focus my energy on one thing at a time, spending my mental energy where it counts the most.

** _Dumbing Down a Phone_
As we approach the present day in this story I began to think more and more about the time I was spending on my phone.

I think most of us have an interal feeling that these phones are somehow harmful, but it's hard to pinpoint where that line should exactly be drawn. For me, I thought just the actual screen time number was the most important metric, so after watching some YouTube videos about "technology lifehacks" I settled on a basic strategy. Removing all extra apps from my phone, turning the phone into grayscale, and turning off notifications. This sounds like a great plan, but it very quickly becomes inconvenient if you do not have the support structure already set up to support this change. And so, the changes never lasted.

However, this grayscale phone idea persisted in my mind, and I would try it out 5-6 more times before I reached the end of my transition period. The issue was that on the iPhone you can bind a tripple-click of the side button to pop open an accessibility menu, allowing you to toggle the phone back to full color. I figured this was just going to be a convenience if I ever needed to see the colors of an image, but it turned out to just be a slippery slope that lead me into almost constantly being in full color mode. This is especially apparent when meeting new people or showing someone an image on your phone, as it sometimes just requires too much social energy to have to explain why your phone is in grayscale, so you end up leaving it off for large periods of time, before eventually forgetting about the grayscale idea all togther.

That was until the end of last year when I came across a video from /f4mi/ about dumb phones from Japan. I had always known about the existance of dump phones, but never thought they would be sustainable for someons of my age group. Yet, she seemed to make a compelling argument that somehow triggered my brain into research mode, trying to discover anything and everything I could about dumb phones. Ironically, this meant spending way more time than usual on my iPhone watching videos from dumb phone influencers (who knew that was a thing) about the quirks and features of the various different models of phones.

One thing I quickly realized is that this was going to be doable, but I had to choose a specific model very carefully. To that vein, I compiled a list of must-have features, and then a list of phones that satisifed this feature list. For me that meant, calling and texting, some form of audio playback, and maps. Not a huge list, but as I found out, finding a true dumb phone with those features was difficult. I ended up initially landing on the Light Phone II, before quickly talking myself out of the whole idea once I realized for one the phone was out of stock and two, it was fetching nearly $200 used on eBay.

Not wanting to give up on the idea all together I came across a video from /Digging the Greats/ talking about his experience going back to an iPod for his primary music playback device. His video series is very intersting but for me the highlight was his observation of the crossroads he found himself at. He wanted to ditch his iPhone, but the was society operates is largely based on smartphones. To this he makes a suggestion of a "launcher" for the iPhone which displays only 5 or so apps on the homescreen by name. I quickly installed the launcher, set everything up, and started living with it. However, it didn't take long for me to simply swipe left and have access to the entire app drawr.

Realzing that this effort would take more than a simple skin on top of my phone I more seriously reconsidered the Light Phone.

* _Going Phone-/less/_

In December of last year I purchased a used Light Phone II from a seller on Reddit (which annoyingly meant I had to create a Reddit account just to facilitate the transaction). In the time it took for the seller to ship the phone I began to set up the support infrastructure for me to ditch the iPhone. Notably, this was the first time I took a methodical and thought out approach to a technology shift, which meant it was far more likely to be a successful endevor.

For me this included transitioning One-Time passwords to an external device, setting up a desktop email client, and shifting my cloud synced notes to a local-first colleciton. The biggest aha moment for me during this process was that I would no longer be reachable by email 24/7, if I wanted to respond to an email I'd have to be sitting at my desk, or using my laptop. The thought of that was scary at first, but I soon realized that the way things are supposed to be. I would no longer feel the temptation to instantly respond to an email while out with friends, I could instead deal with my inbox on my own time, when I was in a mode ready to do so.

The only thing I haven't been able to move away from is my school's ID card system. Sadly this system is dependent on you carrying around a smartphone for building access, paying for meals, and getting into sporting events. Some time before I enrolled they decided to stop issuing physical ID cards, so for now I continue having to carry my iPhone so that I can enter buildings. This is the sad reality that we live in, carrying a smartphone is now the default state, and if you choose not to the world isn't going to work for you like it does for everyone else.

** _Switching Over_

The switch from iPhone to Light Phone was entirely painless, all I did was pop the sim card out of one and into the other. I don't want to dive too specifically into the Light Phone here, but their online dashboard works just fine for loading in contact, syncing music, and subscribing to podcasts.

Once I had fully switched over I started going about my days just as I normally had, just without a constant source of YouTube and Reddit ready to go. The only issue was, I was still listening to podcasts as often as I could. The feature that I thought would be entirely necessary for me to switch over ended up being the feature that I should have avoided. But surely I couldn't subscribe to enough podcasts to fill every hour with every day right? Well that was true, but the Light Phone also allows you to load "music" onto the device, which in my eyes meant ripping YouTube videos to mp3, and loading them onto the device.

So we were essentially right back where we started, just with a slightly more clunky user interface. This continued on for a while, and I definetly noticed some immediate improvements. For one, being less distracted has lead to me focusing all of my energy into building relationships with the people I am constantly around, yet at the same time it has led to me being all the more frustrated by everyone else's constant device usage. To solve my own frustration I have implemented a simple rule, if someone feels the need to pick up a device in the middle of our conversion I will just stop talking. While not always effective it surely makes for some long awkward pauses in what would be a perfectly normal conversation.

The next benefit is being more focused, and I'm not just talking about not having social media to distract me. No, what I mean is when I sit down at my computer now I know this is the only place where I can get work done. There is no longer the temptation to not reply to an email, or not submit an assignment, as I know if I don't do it on my computer it won't get done. This also has the benefit of meaning I need to be very focused with my time, otherwise I will end up spending far more than my minimum 8 hours at the computer to ensure all of my work gets done.

The last overall benefit is embracing other forms of entertainment, and this led me into the final chapter of this story. I started reading again, at first just technical books, real boring stuff about algorithms, different UNIX style tools, and compiler theory. Reading is a very valuable way to gain information, yet it always felt much slower than video or audio, and I never appriciated why. There is typically a certain bar of entry, a stamp or approval, or quality control, that comes along with publishing a book. This means that typically, the level of effort put into a book can be vastly higher than a YouTube video, and this is not to say that there aren't YouTube videos which required more effort than a book, or the other way around. This is just an observation that books have been vetted over year and years, with thousands of people recommending them, and those books are usually worth the read.

One particular book that kept poping up in my research around dumb phones, and the general lifestyle associated with it was /Digital Minimalism/ by Cal Newport. Just from hearing the title it sounded like my kind of book, but I felt as thought I was already leading a digital minimalist lifestyle, so I didn't bother to pick up the book right away. That was until I was browing the Library website for another book and happened to remember the title, I punched it in the search bar, and sure enough it was available. I checked out the book and began reading it the follow day.

* _Digital Minimalism_

That now brings us to pretty much present day (about a week ago), where I have read through the entire book, and am currently on my month-long break from optional technology. For me this means no YouTube, no podcasts, and no hacker news (I kicked Reddit a while back). The book covers a wide range of supporting topics surround digital minimalism, the two the that stuck out the most to me being /solitude/ and /leisure/.

** _Solitude_

What I took from the chapter on solitude was that we as humans need time uninterrupted by thoughts from others, which is very different to how I would have described solitude before reading the book. The key example that stood out to me was going into a loud/busy coffee shop while sitting down to write a paper. While you are surrounded by plenty of other people, they are not impacting your thoughts or emotions at that moment.

A coffee shop isn't the common place for me, but this example almost perfectly translates to my walks. I take somewhere between 3–4 walks a day, and up until now these walks have always been my time to listen to podcasts. The interesting thing was, I'd walk so frequently that I'd run out of podcasts, and then I'd get frustrated that I had nothing to listen to. This leads me to ripping YouTube videos to mp3 before each and every walk so that I'd never have to have even a moment of silence on a walk. Looking back on this now it seems so silly, but I had been doing this for a long time, just in different forms.

The other big thing impacting my solitude was YouTube. Every single day I'd get up, make breakfast and a coffee, then go sit down to watch whatever /someone else/ had published. This was then followed up by a walk where I'd listen to a podcast, finally coming back home to get work down, without ever giving my mind the space that it needed to process what it needed to. This once again seems silly, but for a different reason, in our current world of always needing to be productive why would you ever not be consuming information or doing work? Well the answer is because we aren't meant to always to "consuming", often times we need to both process our own thought, or produce new ideas of their own.

A shower thought is the perfect example of this phenomenom. Most people (I hope?) are distraction free while taking a shower, and for this reason our mind is left to wander. Generally, nothing profound will come out of this time, but every once in a while you may have a breakthrough on something you've been thinking about. The thing is, this doesn't have to only occur during a shower. Instead of filling small pockets of your life with entertainment, you can instead live alone with your thoughts for a brief period of time. From experience, this is very difficult at first, hence why I am taking the time to write this post today, as it has been the most difficult day so far to avoid temptations.

Solitude also means taking the time to be away from your phone, or more generally technology. Even with a dumb phone there are still notifications, are there may still be the urge to check for a response. This can impact your solitude and not let your mind wander to the places that it would like to go, therefore it is important that your times of solitude are spent truely removed from external distraction.

** _Leisure_

Leisure is a much harder topic for me, as I enjoy coding for fun, but that inherently is not a tech-free activity. As I said before I am about a week in to my digital detox, and other than reading, I have not found any suitable high-quality leisure activites that I can add to my schedule. However, reading has been very productive, and it is something I'd like to keep up with.

I am also going to try and write down more of my thoughts as them come along, whether of not those turn in to posts remains to be seen.

This is an area I need to spend more focused time into exploring, and I hope to do so in the remaining weeks of my digital detox.

** _Social Thoughts_

With some of my extra time I've been putting a lot of thought into the relationships that I maintain. The baseline thought that has been going through my head is that I have no desire to maintain many surface level friendships, and that I'd much rather have a few much more genuine face-to-face connections. I also personally find it very difficult to maintain relationships with people I no longer see on regular basis, this may come down to having fewer things in common, or just me preferring human interraction as opposed to liking a text message.

Along the same line as the above thought, I am embracing community in a much more serious way than I previously had. I picked up climbing this past summer, and while it can be a solo activity (bouldering), I've found that I much more enjoy going to the gym and working on hard climbs with people much stronger than me. Or maybe even giving a newer climber pointers on achieving their next V grade. These aren't specific one-on-one relationship, they are more so community building relationships where I feel at home in a particual place, able to interract with like-minded people.

Another key thing I've thought about is making myself both more available and less available. More available in the sense that when I'm interracting with someone face-to-face I often shut my laptop screen, even if it would be beneficial to google something, I want them to know they have my full attention. Less available in the sense that I am no longer going to maintain many sparse communication channels, just in case someone needs my attention or help. I am going to priortize the people around me, choosing to help them first, and directing to find me in a meeting place.

As I was previously a Teaching Assistant for my college a lot of students think I am constantly available to help solve their issues. Some of my peers handle this in a very respectful manner, asking when I am available, and coming with a pre-formed question, along with all the background information to explain the context. To these students I say thank you, and I am often able to solve their problem relatively quickly, and if I can't, no harm no foul. My issue is with the large majority of my peers who either have no desire to learn and just want my solutions, or they have a desire to "learn", as long as learning means me solving their problem.

To address the second group of students I have employed a new strategy to handle their behavior in what I feel is a respectful manner. For one, I no longer immedietly respond to texts asking for help, as often they will solve the problem on their own if left to sit and think for an hour. Second, if they have not provided me with any background information I will ask the simple question "What have you tried?". Lastly, if they don't ask a question at all, instead just asking for help on some vague topic I will respond with "What is your question?". These 3 rules seem to eliminate roughly half of all the requests I was previously dealing with, only falling short for the most insessent of students.

For these remaining students I really struggle with what to do, often resorting to communicating less and less so that they hopefully view me as less of a crutch. This is something I really struggled with during my first semesters as a TA. I wound up sitting and helping people with programming labs start to finish, leaving myself no time to explore coding on my own, and even now I often find myself doing this. This is a hard one because I personally would never ask a TA or Professor for anything but clarification on an assignment, as I know other students have previously completed the assignment, therefore it is clearly possible. Yet, I know I am not in the majority with this opinion, so I struggle to find a balance when those questions are asked of me.

This small section highlights just a few of the ideas I've had time to mull over now that I've allowed my mind to have periods of solitude to think. They're not fully flushed out ideas, nor are they all good! All of the above are very fluid in my mind and may change, I'm just glad I have the space now to think through some of these things.

* _Where I'm At_
As I currently sit writing this I am a week into my digital detox, and I think I'd like to continue like this. At this moment I don't see myself going back to watching YouTube, or listening to podcasts 24/7. I do however think that I'll listen to podcasts during my drives as keeping up with least some of the latest tech news is a good plan, especially in my field.

As for the rest of my detox I plan to find more forms of high-quality leisure outside of reading, and to write down my most pertinant thoughts as they come along.

I think this write-up ended up being a lot more focused on lifestyle than I originally planned, but as I've come to realize that is the more important piece of the whole puzzle. Now that I've become detached from my phone I see it as nothing more than a hindrence to the rest of my left, and now I never plan to go back.

#  LocalWords:  f4mi
