#+title: One Three

* Objectives
- Add and subtract matricies
- Multiply matricies
- Writing a system of linear equations as a matrix product
- Write a matrxi product as the linear combination of the columns
- Compute the tract and transpost of a matrix

* Consistent Factors
A matrix with /m/ rows and /n/ columns is called an /m/ by /n/ matrix
Every location in a matrix A is double subscripted
The a_{i,j}th number is found in the /i/th row and /j/th column
3 by 4 matrix
5, 9, 3
Row matricies have one row for example, column matricies have one column, also called vector

* Matrix Arithmetic
** Defintion
Two matricies A and B are equal, if they have the same dimension (m x n), and their corresponding entries are identical. (A)_{ij} = = a_{ij} = b_{ij} = (B)_{ij} for 1 <= /i/ <= m, and 1 <= /j/ <= /n/

** Addition/Subtraction
Two matricies have a sumer or different if and only if they have the same dimensions (m x n), and their sum is defined to be (A + B)_{ij} = a_{ij} + b_{ij}

| 1 | 2 | 4 |
| 1 | 3 | 9 |
+
| 2 | 3 | 6 |
| 4 | 5 | 20 |
=
| 3 | 5 | 10 |
| 5 | 8 | 29 |

| 1 | 3 |
| 4 | 7 |
| 2 | -1 |
-
| 4 | 2 |
| 1 | 3 |
| 0 | 6 |
=
| (-3) |  1 |
|    3 |  4 |
|    2 | -7 |

** Definition
If A is an m x n matrix and c is a scalar, then the *scalar multiple* of A by c is the m x n matric given by cA = (ca_{ij})

1.
|  7 | 63 |
| 56 |  -14 |
2.
| ka | kb | kc |
| kd | ke | kf |
3.
| 0 | 0 |
| 0 | 0 |
| 0 | 0 |
4.
| 16 | 5 |
|  2 | 13 |

** Definition
Two matricies A and B can be multiplied if and only if the number of columns of A matches the number of rows of B

A_{m x n}B_{n x p} = C_{m x p}
and (AB)_{ij} = \Sum{k=1}{n}a_{ik}b_{kj} = a_{i1}b_{1j} + a_{i2}b_{2j} + a_{i3}b_{3j} + ... + a_{in}b_{nj}

If A is 3x4 and B is 4x5 => 3x5
If A is 3x4 and B is 3x4 => invalid multiplication

*** How-to Matrix Multiply
Row /i/ times column /j/

**** 1
#+begin_src octave :results none
a = [1,3]
b = [a,b;c,d]
a * b
#+end_src

row1 = [1,3] & column1 = [a;c]
turns into
1(a) + 3(c) = a+3c

row1 = [1,3] & column2 = [b;d]
turns into
1(b) + 3(d) = b+3d

| row1*colum1 | row1*column2 |
|-------------+--------------|
| a+3c        | b+3d         |

**** 2
#+begin_src octave
a = [0,-1;1,0]
b = [5;1]

a * b
#+end_src

#+RESULTS:
| -1 |
|  5 |

| 0(5)+(-1)1 |
|  1(5)+0(1) |

| (-1) |
|    5 |
|      |
**** 3
#+begin_src octave
a = [1,2;3,4;5,6]
b = [4,3;5,1]

a * b
#+end_src

#+RESULTS:
| 14 |  5 |
| 32 | 13 |
| 50 | 21 |

| 1(4)+2(5) | 1(3)+2(1) |
| 3(4)+4(5) | 3(3)+4(1) |
| 5(4)+6(5) | 5(3)+6(1) |

| 14 |  5 |
| 32 | 13 |
| 50 | 21 |
**** 4
| a_{11} | a_{12} |
| a_{21} | a_{22} |
and
| b_{11} | b_{12} |
| b_{21} | b_{22} |

| a_{11}(b_{11}) + a_{22}(b_{21}) | a_{11}(b_{12}) + a_{12}(b_{22}) |
| a_{21}(b_{11}) + a_{22}(b_{21}) | a_{21}(b_{12}) + a_{22}(b_{22}) |
**** 5
| 1(5)+2(6) | 1(-1)+2(7) |
| 3(5)+4(6) | 3(-1)+4(7) |

| 17 | 13 |
| 39 | 25 |
**** 6
| 5(1)+-1(3) | 5(2)+-1(4) |
|  6(1)+7(3) | 6(2)+7(4)  |

|  2 | 6 |
| 27 | 40 |
**** 7
| 1(1)+3(4)+5(6) | 1(6)+3(1)+5-1) |

* Coefficient Matrix
[A|b] where A are the left hand side, b is the right hand side of the equals sign

* Linear Combination
Matrix product as linear combination

** Theorem
If A_{m x n} and x_{n x 1}, then Ax can be expressed as a linear combination of the column vectors of A in which coefficients are the entires of X(vector)

In general: A_{x} = [column 1]x_{1} + [column 2]x_{2} + ... + [column n]x_{n}

* Transpose a Matrix
If any m x n matrix is transposed then it's dimensions will become n x m, row of A becomes column of A_{T}

\[(A^{T})_{ij} = (A)_{ji}\]

* Trace of a Matrix
If A is a square matrix, then the tract of A, denoted by *tr(A)* is defined to be the sum of the entries on the main diagonal of *A*. The trace of A is undefined if A is not a square matrix.

* Matrix Polynomials
Given $2x^{2}-3x+4$ find f(a)
We need to add an 'I' that is the same dimensions as the matrix, in this case 4I_{2}
#+begin_src octave
A = [4,1;3,5]

2 * (A * A) - (3*A) + 4*eye(2)

2*[19,9;27,28]-[12,3;9,15]+[4,0;0,4]
#+end_src

#+RESULTS:
| 30 | 15 |
| 45 | 45 |

* The Inverse of a Square Matrix
Any nxn matrix A is said to be invertible, or nonsingular, if there exists a matrix B such that AB = I = Ba.
The inverse is written as A^{-1}
If A has no inverse it is said to be singular

Need to check if AB = I && BA = I

If you multiply a matrix and its inverse you should get the identity matrix of the same size
** Given A = [5,1;4,1] and B = [1,-1;-4,5], check if A and B are inverses
We take [a,b;c,d] -> [d,-b;-c,a]

#+begin_src octave
a = [5,1;4,1]
b = [1,-1;-4,5]

b*a
#+end_src

#+RESULTS:
| 1 | 0 |
| 0 | 1 |

** Given A = [1,3;1,6] and B = [2,-1;-1/3,1/3] check if A and B are inverse
#+begin_src octave
A = [1,3;1,6]
B = [2,-1;-1/3,1/3]

A*B
#+end_src

#+RESULTS:
| 1 | 0 |
| 0 | 1 |

** Theorem
A matrix A is only invertible if $ad-bc \neq 0$, in which case the inverse is given by the formula

\[
A^{-1} = \frac{1}{ad-bc}\begin{bmatrix}d & -b \\ -c & a\end{bmatrix}
\]

$ad-bc$ is called the determinant of the matrix A (cross multiply)

** Practice
#+begin_src octave
a = [1,2;3,4]
b = [-1,2;3,-2]
c = [2,-1;-4,2]

inv(a)
#+end_src

#+RESULTS:
|  -2 |  0.9999999999999998 |
| 1.5 | -0.4999999999999999 |

** Why Inverse Matrix?
Helps us to solve a linear system

Given a matrix equation A \rightarrow{}_{x} = b^{\rightarrow{}}, we could solve the equation by applying A^_{-1} to both sides to get
\[
A^{-1}Ax^{\rightarrow{}} = A^{-1}b^{\rightarrow}
\]
\[
x^{\rightarrow} = A^{-1}b^{\rightarrow{}}
\]

Note, if A^{-1} does not exist, the the equation has no solutions

*** Examples
Solve the system by matrix inversion

\[
x_{1}+2x_{2} = 4
3x_{1}+4x_{2} = 10
\]

\[
 \begin{bmatrix}1 & 2 \\ 3 & 4\end{bmatrix} \begin{bmatrix}x_{1}\\x_{2}\end{bmatrix} = \begin{bmatrix}4\\10\end{bmatrix}
\]

\[
A^{-1} = \begin{bmatrix}-2&1\\\frac{3}{2}&\frac{-1}{2}\end{bmatrix}
\]

A * A^{-1} results in I matrix, so $x^{\rightarrow{}} = a^{-1}b^{\rightarrow{}}

\[
\begin{bmatrix}-2&1\\\frac{3}{2}&\frac{-1}{2}\end{bmatrix}\begin{bmatrix}4\\10\end{bmatrix}
\]

\[
\begin{bmatrix}x_{1}\\x_{2}\end{bmatrix}\begin{bmatrix}-2(4)+1(10)\\\frac{3}{2}(4)+\frac{-1}{2}(10)\end{bmatrix}
\]

\[
\begin{bmatrix}x_{1}\\x_{2}\end{bmatrix} = \begin{bmatrix}2\\1\end{bmatrix}
\]

x_{1} = 2 and x_{2} = 1


** Properties of Inverses
1. If an nxn matrix A is non-singular then A^{-1} is unique
2. If A and B are nxn non-singular matricies, then AB is nonsingular, and (AB)^{-1} = B^{-1}A^{-1}
3. (A^{-1})^{-1} = A
4. (kA)^{-1} = \frac{1}{k}A^{-1}
5. (A^{T})^{-1} = (A^{-1})^{T}

** Solve for D
Suppose A,B,C,D are all nxn nonsingular matricies
- Solve for d: AB^{-1}DBA^{-1} = C

the answer is BA^{-1}CAB^{-1}

** The Cancellation Law
Work in the case in which we are dealing with an invertible matrix
