#+title: One One
#+options: toc:nil \n:t
#+setupfile: ./jake.setup

* Objectives
- Given a system of linear equations, identify if the system has, 0, 1 or infinte solutions
- Given a system of linear equations, identify if the system is a homogenous system
- Transform Systems of linear equations into augmented coefficient matricies
- Solve systems of linear equations using Gauss-Jordan reduction
- Translate the reduced row echelon form of the matrix to a solution to the system

* Systems of Equations => Matricies
We can represent the system of equations

\begin{matrix}
5x+y=3\\
2x-y=4
\end{matrix}

\begin{array}{cc|c}
5 & 1 & 3 \\
2 & -1 & 4
\end{array}

\left(
\begin{array}{ccc}
1 & 0 & 3\\
1 & 0 & 3
\end{array}
\right)

* Review of SOE
Recall that 2D is represented as $ay + by = c$, where (a != 0 and b != 0)
and 3D is represented as $ay + by + cz = d$, once again (a,b,c != 0)

We can define a more general form
\[
a_{}x_{1} + a_{2}x_{2} + ... + a_{n}x_{n} = b
\]

where a_{1}, a_{2},...,a_{n} and b are real constants

** Examples
$x + 3y = 7$
$x_{1}-2x_{2}-3x_{3}+x_{4}=0$
$\frac{1}{2}x-y+3z=-1$
$x_{1}+x_{2}+...+x_{n}=1$

** Non-examples
$x+3y^{2}=4$
$3x+2y-xy=5$
$sinx+y=0$
$\sqrt{x_{1}}+2x_{2}+x_{3}=1$

** Terminology
We call these finite sets of linear equations a *linear system*, where the variables are called *unknowns*.

A general linear system of m equations in the n unknowns x_{1},x_{2},...,x_{n} can be written as

\begin{matrix}
a_{11}x_{1} + a_{12}x_{2} + ... + a_{1n}x_{n} = b1\\
a_{21}x_{1} + a_{22}x_{2} + ... + a_{2n}x_{n} = b2\\
...\\
a_{m1}x_{1} + a_{m2}x_{2} + ... + a_{mn}x_{n} = bm\\
\end{matrix}

A solution of a linear system in n unknowns x_1,x_2,...,x_n is a sequence of n numbers s_1,s_2,...,s_n for which the substitution
\[x_1 = s_1, x_2 = s_2, ..., x_n = s_n\]
makes each equation a true statement. Generally we could write solutions as
\[(s_1,s_2,...,s_n\]
which as called an ordered n-tuple. With this notation it is understood that all variables appear in the same order in each equation. If n = 2, then the n-tuple is called an *ordered pair*, and if n = 3, then it is called an *ordered triple*.

** Solve the Systems:
In linear algebra we mostly focus on elimination method
*** 1.
\begin{matrix}
x & + & y & = & 10 & (1))\\
3x & + & y & = & 18 & (2)
\end{matrix}

$(1)-(2)$
$-2x = -8$
$3x + y = 18$

$x=4$
$3(4) + y = 18$

$x = 4$
$y = 6$

$(4,6)$
*** 2.
\begin{matrix}
x & + & y & = & 10\\
3x & + & 3y & = & 30
\end{matrix}
*** 3.
\begin{matrix}
x & + & y & = & 10\\
3x & + & 3y & = & 18
\end{matrix}
*** 4.
\begin{matrix}
x & + & y & = & 0\\
4x & + & 5y & = & 0
\end{matrix}

** Solutions to Linear Systems
| # of solutions  | title        |
|-----------------+--------------|
| at least one    | consistent   |
| no solutions    | inconsistent |
| \inf{}          | dependent    |
| all solutions 0 | homogenous   |

** How to Write out Systems
\begin{matrix}
a_{11}x_{1} + a_{12}x_{2} + ... + a_{1n}x_{n} = b1\\
a_{21}x_{1} + a_{22}x_{2} + ... + a_{2n}x_{n} = b2\\
...\\
a_{m1}x_{1} + a_{m2}x_{2} + ... + a_{mn}x_{n} = bm\\
\end{matrix}

\left (
\begin{array}{cccc|c}
v1 & v2 \
a_{11} & a_{12} & ... & a_{1n} & b_1\\
a_{21} & a_{22} & ... & a_{2n} & b_2\\
...\\
a_{m1} & a_{m2} & ... & a_{mn} & b_m
\end{array}
\right )

This is called the augmented matrix for the system

*** Example from College Algebra
\left (
\begin{array}{cccc|c}
x_1 & + & 2x_2 & = & 16\\
2x_4 & + & 3x_2 & = & 16
\end{array}
\right )

Check if (2,4) is a solution

*** Example 1 Show the Augmented Matrix
\begin{bmatrix}
1 & 1 & 2 & | & 9\\
2 & 4 & -3 & | & 1\\
3 & 6 & -5 & | & 0
\end{bmatrix}

# \begin{array}{ccc|c}
# 1 & 1 & 2 & 9\\
# 2 & 4 & -3 & 1\\
# 3 & 6 & -5 & 0
# \end{array}

We have to rewrite equations if needed before writing out the corresponding augmented matrix

\begin{Bmatrix}
x_1 & + & 2x_2 & = & 3\\
3x_2 & + & x_1 & = & 1
\end{Bmatrix}

Move x_1 and x_2 to line up with each other, forming...

\begin{bmatrix}
1 & 2 & | & 3\\
1 & 3 & | & 1
\end{bmatrix}

** How to Solve a Sytem Using Matricies
We need to perform operations on the system that do not alter the solution set and that produce a succession of increasingly simpler systems, until a point is reached where is can ascertained whether the system is consistent, and if so, what its solutions are.

*** Common Steps
1. Multiply an equation through by a by a nonzero constant
2. Interchange two equations
3. Add a constant times one equation to another
   - Adding or subtracting
   - 3 - 4 = (3 + -4)

Since the rows of an augmented matrix correspond to the equation in the associated system, these t3 operations correspond to the following operations on the rows of an augmented matrix
1. Multiply a row through by a nonzero constant
2. Interchange two rows
3. Add a constant time one row to another

These are called elementary row operations on a matrix

**** Example 2
Solve the following by starting with an augmented coefficent matrix

\begin{matrix}
x & + & 4y & = & 19\\
3x & + & y & = & 2
\end{matrix}

\left (
\begin{array}{cc|c}
1 & 4 & 19\\
3 & 1 & 2
\end{array}
\right )

How to solve the problem?
$R_2 - 3R_1 \rightarrow{} R_2$

3R_1:
[3 12 57]

\left (
\begin{array}{cc|c}
1 & 4 & 19\\
0 & -11 & -55
\end{array}
\right )

$-11y = -55$
$y = 5$

$x + 4(5) = 19$
$x = -1$

$(-1, 5)$

**** Example 3
We will come back to this after 1.2
\begin{matrix}
x & + & y & + & 2z & = & 9\\
2x & + & 4y & - & 3z & = & 1\\
3x & + & 6y & - & 5z & = & 0
\end{matrix}
