#+title: Three One
A vector is characterized by 2 quantities, length and direction. Geometrically a vector in the plane is represented by a direct line segments with its initial point at the origin and its terminal point (x,y). We will consider vectors as objects of Vector spaces.

By R^{n} we mean all vectors with n componenets, and in each component is a real number.

* Alternative Notation for Vectors
Comma delimited form v = (v_{1},v_{2},v_{3},...v_{n})
Row-vector form v = [v_1 v_2 v_3 ... v_n]
Column vector form $\begin{bmatrix}v_{1}\\v_{2}\\v_{3}\\...\\v_{n}\end{bmatrix}$

** Facts
- Vectors with the same length and directions are equivalent
- Zero vector, inital and terminal points coincide
- Parallel and colinear mean the same thing when applied to vectors
  - colinear = One vector is a multiple of the other
- Vectors whose inital point is not at the origin:
  - P_{1}P_{2}^{\Rightarrow{}} denotes the initial point P_{1}(x_{1},y_{1}) and terminal point P_{2}(x_{2},y_{2}). The components are P_{1}P_{2}^{\Rightarrow{}} = (x_{2}-x_{1},y_{2}-y_{1})
- The linear combination of vectors v_{1},v_{2},v_{n} is k_{1}v_{1} + k_{2}v_{2} + k_{n}v_{n}, where the k_{i}'s are scalars, or real numbers

* Length (Magnitude)
Sqrt of the sum of each component squared
* Unit vector in the same direction
$\frac{u}{||u||}$
* Write vector as a linear combination of (1,0) & (0,1)
$v^{\rightarrow{}} = a \times (1,0) + b \times (0,1)$ for some real numbers a,b
So, $(2,5) = a(1,0) + b(0,1)$, where a = 2, and b = 5

* For vectors (1,5,4) and (2,7,-4) find all vectors w such that w can be written as a linear combination of u and v
$w = (w_{1},w_{2},w_{3})$
$w = a(1,5,4) + b(2,7,-4)$
$w_{1} = a+2b$
$w_{2} = 5a+7b$
$w_{3} = 4a-4b$
$\begin{bmatrix}1&2&w_{1}\\5&7&w_{2}\\4&-4&w_{3}\end{bmatrix}$
$r_{2}-5r_{1} \rightarrow{} r_{2}$
$r_{3}-4r_{1} \rightarrow r_{3}$
$\begin{bmatrix}1&2&w_{1}\\0&-3&w_{2}-5w_{1}\\0&-12&w_{3}-4w_{1}\end{bmatrix}$
$r_{3}-4r_{2}\rightarrow{}r_{3}$
$\begin{bmatrix}1&2&w_{1}\\0&-3&w_{2}-5w_{1}\\0&0&w_{3}-4w_{1}-4(w_{2}-5w_{1})\end{bmatrix}$
- To have solution we need to make the RHS of row 3 = 0
$w_{3}-4w_{1}-4(w_{2}-5w_{1}) = 0$
$w_{3}+16w_{1}-4w_{2} = 0$

let y = w_{2}, x = w_{1}
$w_{3} = 4y - 16x$
So, w^{\rightarrow{}} = any vector such that (x,y,4y-16x) where x,y \in{} \mathbb{R}
